language: objective-c
osx_image: xcode8.1sneakpeek

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew upgrade carthage
  - gem install xcpretty
  - carthage bootstrap --platform mac

script:
  - set -o pipefail 
  - xcodebuild -project HSTracker.xcodeproj -scheme HSTracker -sdk macosx clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty

